version: '3.8'

services:
  fastapi-app:
    image: waiting-app
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - mongo-db
    volumes:
      - ./backend:/app/backend
      - waiting-volume:/app/data
      - "../business-post:/app/business-post"

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=waiting
volumes:
  waiting-volume: